### PR TITLE
Tmtravlrs branch

### PR DESCRIPTION
**Pull request by Tmtravlr**
Added dimension code, and updated biome code.

### CODE REVIEW

**Comment by MrIbby** [comment]
Proper naming would be helpful :P

**Comment by Ghostrec35** [comment]
Fix small issues like that and I'm 100% for merging this with the master branch. Everything seems to be in order.

**Comment by Ghostrec35** [comment]
Not sure if any of what's in here is still needed or desired. Either way, it will need to be redone before another pull can be made.

**Pull request closed without merging**
